/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20VotesSol from "./ERC20Votes.sol";
export * as myErc20Sol from "./MyERC20.sol";
export { Ballot__factory } from "./Ballot__factory";
export { HelloWorld__factory } from "./HelloWorld__factory";
export { TokenSale__factory } from "./TokenSale__factory";
