/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20VotesSol from "./ERC20Votes.sol";
export type { erc20VotesSol };
import type * as myErc20Sol from "./MyERC20.sol";
export type { myErc20Sol };
export type { Ballot } from "./Ballot";
export type { HelloWorld } from "./HelloWorld";
export type { TokenSale } from "./TokenSale";
